project_name: deckhand

before:
  hooks:
    - go mod tidy

builds:
  - id: deckhand
    main: ./cmd/deckhand
    binary: deckhand
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: unix
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
  - id: windows
    formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    builds:
      - deckhand

checksum:
  name_template: checksums.txt
