apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
  labels:
    app.kubernetes.io/part-of: deckhand-lab
    deckhand.io/scenario: pending
spec:
  nodeSelector:
    kubernetes.io/hostname: definitely-not-a-real-node
  containers:
    - name: sleeper
      image: alpine:3.20
      command: ["/bin/sh","-c"]
      args: ["sleep 3600"]
